# Generated by Django 2.2.6 on 2019-10-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='jk',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
