# Generated by Django 2.2.6 on 2019-10-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_customer_gaji'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alamat',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='existing',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
