# Generated by Django 2.2.6 on 2019-10-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_auto_20191030_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='jk',
            field=models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='occupation',
            field=models.CharField(choices=[('N', 'NON-FIX'), ('F', 'FIX')], default='F', max_length=5),
        ),
    ]
